apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: flask-demo
type: Opaque
data:
  DB_NAME: ${{ DB_NAME }}
  DB_USERNAME: ${{ DB_USERNAME }}
  DB_PASSWORD: ${{ DB_PASSWORD }}
  DB_HOST: ${{ DB_HOST }}
  DB_PORT: ${{ DB_PORT }}
